package com.wtwd.translate.bean.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wtwd.translate.bean.User;
import com.wtwd.translate.bean.RecorderBean;
import com.wtwd.translate.bean.Guest;

import com.wtwd.translate.bean.dao.UserDao;
import com.wtwd.translate.bean.dao.RecorderBeanDao;
import com.wtwd.translate.bean.dao.GuestDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig recorderBeanDaoConfig;
    private final DaoConfig guestDaoConfig;

    private final UserDao userDao;
    private final RecorderBeanDao recorderBeanDao;
    private final GuestDao guestDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        recorderBeanDaoConfig = daoConfigMap.get(RecorderBeanDao.class).clone();
        recorderBeanDaoConfig.initIdentityScope(type);

        guestDaoConfig = daoConfigMap.get(GuestDao.class).clone();
        guestDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        recorderBeanDao = new RecorderBeanDao(recorderBeanDaoConfig, this);
        guestDao = new GuestDao(guestDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(RecorderBean.class, recorderBeanDao);
        registerDao(Guest.class, guestDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        recorderBeanDaoConfig.clearIdentityScope();
        guestDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public RecorderBeanDao getRecorderBeanDao() {
        return recorderBeanDao;
    }

    public GuestDao getGuestDao() {
        return guestDao;
    }

}
